# Generated by Django 5.2.5 on 2025-08-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeaderContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gif", models.ImageField(upload_to="gifs/")),
                ("comment", models.CharField(max_length=200)),
                ("cover_image", models.ImageField(upload_to="covers/")),
                ("video_link", models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name="Description",
        ),
        migrations.DeleteModel(
            name="ImageAsset",
        ),
        migrations.DeleteModel(
            name="SocialLink",
        ),
    ]
